# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)

# hyperparameters of training
momentum: 0.9
decay: 0.0001
learning_rate: 0.00125  # 1 device training
epochs: 30
batch_size: 4
warmup_steps: 8000
accumulate_batches: 1

# other
num_classes: 1
img_size: [1088, 608]
img_scale: 255
img_mean: [0.485, 0.456, 0.406]
img_std: [0.229, 0.224, 0.225]
track_buffer: 30
log_step: 100

# model initialization parameters
backbone_layers: [1, 2, 8, 8, 4]
backbone_input_shape: [32, 64, 128, 256, 512]
backbone_output_shape: [64, 128, 256, 512, 1024]
out_channel: 24  # 3 * (num_classes + 5)
embedding_dim: 512

# evaluation thresholds
iou_thres: 0.50
conf_thres: 0.55
nms_thres: 0.45
min_box_area: 200

# h -> w
anchor_scales: [
      [8, 24],
      [11, 34],
      [16, 48],
      [23, 68],
      [32, 96],
      [45, 135],
      [64, 192],
      [90, 271],
      [128, 384],
      [180, 540],
      [256, 640],
      [512, 640],
]

# other
is_distributed: False
dataset_root: '/root/path/to/dataset/JDE'
ckpt_url: '/path/to/checkpoint'
pretrained_path: 'pretrained/darknet53.conv.74'
logs_dir: 'logs'
input_video: '/path/to/input/video'
output_format: 'video'
output_root: 'results'
save_images: False
save_videos: False
num_workers: 8

---
# Config description for each option
momentum: 'Momentum for SGD optimizer.'
decay: 'Weight_decay for SGD optimizer.'
learning_rate: 'Init learning rate.'
epochs: 'Number of epochs to train.'
batch_size: 'Batch size per one device'
warmup_steps: 'Number of the warmup steps during training.'
accumulate_batches: 'Number of batches to accumulate gradient.'
num_classes: 'Number of object classes.'
k_max: 'Max predictions per one map (made for optimization of FC layer embedding computation).'
img_size: 'Size of input images.'
track_buffer: 'Tracking buffer.'
keep_checkpoint_max: 'Keep saved last N checkpoints.'
backbone_input_shape: 'Input filters of backbone layers.'
backbone_shape: 'Input filters of backbone layers.'
backbone_layers: 'Output filters of backbone layers.'
out_channel: 'Number of channels for detection.'
embedding_dim: 'Number of channels for embeddings.'
iou_thres: 'IOU thresholds.'
conf_thres: 'Confidence threshold.'
nms_thres: 'Threshold for Non-max suppression.'
min_box_area: 'Filter out tiny boxes.'
anchor_scales: '12 predefined anchor boxes. Different 4 per each of 3 feature maps.'
is_distributed: 'Distribute training or not.'
dataset_root: 'Path to datasets root folder.'
device_id: 'Device id of target device.'
device_start: 'Start device id.'
ckpt_url: 'Location of checkpoint.'
logs_dir: 'Dir to save logs and ckpt.'
input_video: 'Path to the input video.'
output_format: 'Expected output format.'
output_root: 'Expected output root path.'
save_images: 'Save tracking results (image).'
save_videos: 'Save tracking results (video).'
num_workers: 'Number of parallel workers of the dataloader.'
